name: Netflix Movie Catalog Service Deployment

on:
  push:
    paths:
      - "src/NetflixMovieCatalog/**"
    branches:
      - main

env:
  EC2_PUBLIC_IP: 34.204.44.168 # Replace with your EC2 instance public IP
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} # Define this secret in your GitHub repo settings

jobs:
  Deploy:
    name: Deploy Netflix Movie Catalog in EC2 via Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the app code
        uses: actions/checkout@v2

      - name: Write SSH private key to file
        run: |
          printf "%s" "$SSH_PRIVATE_KEY" > mykey.pem
          chmod 600 mykey.pem

      - name: Create directory on EC2 if it does not exist
        run: |
          ssh -o StrictHostKeyChecking=no -i mykey.pem ubuntu@$EC2_PUBLIC_IP "if [ ! -d ~/NetflixMovieCatalog ]; then mkdir ~/NetflixMovieCatalog; fi"

      - name: Copy deploy.sh to EC2
        run: |
          # Copy the deploy.sh script to the EC2 instance
          scp -o StrictHostKeyChecking=no -i mykey.pem src/NetflixMovieCatalog/deploy.sh ubuntu@$EC2_PUBLIC_IP:~/NetflixMovieCatalog/deploy.sh

      - name: SSH to EC2 and run deploy.sh
        run: |
          # SSH into the EC2 instance and execute the deploy.sh script
          ssh -o StrictHostKeyChecking=no -i mykey.pem ubuntu@$EC2_PUBLIC_IP "bash ~/NetflixMovieCatalog/deploy.sh"
